### ISSUE TITLE
Erweiterung für Exceptionhandling für -cfg: Prüfung ob Format und Inhalt in Ordnung sind, sodass der Parameter korrekt verwendet werden kann

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#109]
Aktuell ist es so, wenn die cfg Datei komplett auskommentiert ist (was passieren kann) oder beispielsweise das Format der Datei nicht passt, das wir bei Ausführung des Parameters gar nichts machen. Mein Vorschlag wäre hier eine Rückmeldung zu geben, wieso nichts passiert. Mein Vorhschlag wäre hier die Rückmeldung zu geben, das etwa das Format der Datei nicht stimmt oder eben das die cfg Datei vollständig auskommentiert wurde und deswegen nicht geladen werden konnte.

Der Verbesserungsvorschlag prüft ob die Datei leer ist, nur Leerzeichen enthält oder komplett auskommentiert ist. Die zweite Prüfung enthält die Prüfung ob ein ungültiges Zeichen wie ! ? = enthält und wirft eine Fehlermeldung aus, in welcher Zeile das ungültige Zeichen entdeckt wurde. Das hilft bei debuggen der Config Datei und der Benutzer weiß wieso ProcDumpEx nichts macht. Falls du noch mehr Ideen für ungültige Zeichen hast, kannst du die ja noch hinzufügen :)

EDIT 17.05.24, 20:01: Ich habe das ganze nochmal etwas überarbeitet, denke damit geht das ganze noch etwas flotter und ist kompakter im Code.

Hierfür müssten wir nur ein paar Zeilen anpassen, siehe Zeile 21ff, Option.Cfg.cs:
```

           		// Get the arguments from the file
		internal string[] GetArgumentsFromFile()
		{
			// Check if the file exists
			if (!File.Exists(FilePath))
			{
				throw new ManageArgumentsException("The specified config path is invalid");
			}

			// Read all lines from the file
			var lines = File.ReadAllLines(FilePath);

			var validLinesList = new List<string>();

			// Iterate through each line
			foreach (var line in lines)
			{
				// Check if the line is not null, not whitespace, and does not start with # or //
				if (!string.IsNullOrWhiteSpace(line) && !line.TrimStart().StartsWith("#", "//"))
				{
					validLinesList.Add(line);
				}
			}

			// Check if the list of valid lines is empty
			if (validLinesList.Count == 0)
			{
				throw new ManageArgumentsException("The specified config file is fully commented out, empty, or contains only whitespace");
			}

			var validLines = validLinesList.ToArray();

			// Iterate through each valid line
			foreach (var line in validLines)
			{
				// Check if the line contains any of the invalid characters
				if (line.IndexOfAny(new[] { '=', '!', '?' }) >= 0)
				{
					throw new ManageArgumentsException($"The format of the config file is incorrect. The line '{line}' contains an invalid character.");
				}
			}

			return validLines;
		}
	}

        internal override Task<bool> ExecuteAsync(ProcDumpExCommand command)
        {
            throw new NotImplementedException();
        }
    }


```

**Comment by PoppyTheDeveloPaw** [comment]
Eingebaut mit @ #116
