### ISSUE TITLE
Anpassung der Exceptionrückmeldung: "To use the parameter "-w" ProcDumpEx must be started as administrator!"

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#11]
Die Rückmeldung ist schon Mal nicht schlecht, aber eigentlich sollte als Rückmeldung kommen

"To use ProcDumpEx must be started as administrator" anstatt "To use the parameter "-w" ProcDumpEx must be started as administrator!"

Reproduzieren lässt sich die Meldung mit folgenden Parametern, wenn ProcDumpEx nicht als Admin gestartet ist:

procdumpex.exe -ma -w -e -pn "notepad.exe"

Sonst könnte man annehmen das ich ProcDumpEx definitiv ohne Adminrechte ja verwenden kann, wenn ich Parameter -w weglasse, was ja nicht stimmt. ProcDumpEx benötigt ja in jedem Fall Adminrechte, damit es funktioniert.

**Comment by Zocoya** [comment]
Wenn ich sogar diese Parameter ausführe ohne Adminrechte:

procdumpex.exe -ma -e -pn "notepad.exe"

und notepad.exe läuft nicht, erhalte ich lediglich folgende Rückmeldung:

"Currently there is no process with the name notepad.exe running. The execution for this process name is terminated."

Was erst einmal korrekt ist, da der Prozess nicht gelaufen ist, aber hier bekomme ich auch keinen Hinweis, das ich ProcDumpEx versucht habe, ohne Adminrechte überhaupt auszuführen.

**Comment by PoppyTheDeveloPaw** [comment]
Geschlossen, da bereits mit #27 sichergestellt ist, dass ProcDumpEx nur noch als Administrator gestartet werden kann
