### ISSUE TITLE
Erweiterung des Exceptionhandling für keinen einegebenen Wert für -et

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#110]
Ich habe gesehen das du für die Zeitangabe ein gutes Exceptionhandling bereits eingebaut hast. Ich hätte einen Vorschlag zur Verbesserung.
Wenn ich für -et keinen Wert eingebe, erhalte ich lediglich die Rückmeldung 
"[ProcDumpExCommandParser]: For the option -et one or more values are expected
[ArgumentManager]: Specified parameters (-et -w -pn notepad.exe) could not be parsed. ProcDumpEx is terminated. Use the parameter "-help" to display examples and allowed parameters"

Wenn wir den Null und WhiteSpace Check minimal erweitern, schaffen wir auch hier eine aussagekräftige Fehlermeldung. Wenn dann für d,h,s immer noch kein Wert festgelegt wird, greift unser anderes Exceptionhandling wieder :)

Siehe Zeile 28 in OptionEt.cs:
```
private TimeSpan ParseStringToTimeSpan(string time)
{
    time = time.Trim();
 
    if (string.IsNullOrEmpty(time))
    {
        throw new ArgumentException("No value provided for -et. Please provide a value in the format 999d23h59m59s.");
    }
 
    if (string.IsNullOrWhiteSpace(time) || string.IsNullOrWhiteSpace(et))
    {
        throw new ArgumentException($"{GetType().GetOption()} expects at least one of the parameters 'd', 'h', 'm', 's' to be defined.");
    }
 
    // Rest of the method...
}

```

**Comment by PoppyTheDeveloPaw** [comment]
Verstehe ich nicht so ganz, bei der Angabe von `-et -w -pn notepad.exe` wird das allgemeine ExceptionHandling getriggert, das dafür sorgt, dass 

"[ProcDumpExCommandParser]: For the option -et one or more values are expected
[ArgumentManager]: Specified parameters (-et -w -pn notepad.exe) could not be parsed. ProcDumpEx is terminated. Use the parameter "-help" to display examples and allowed parameters"

ausgegeben wird.

Wenn man Beispielsweise `-et "" -w -pn notepad.exe` angibt, dann ist ein Parameter vorhanden und folgendes wird ausgegeben: "-et expects at least one of the parameters 'd', 'h', 'm' or 's' to be defined."

Das was du als Beispiel angegeben hast würde nur dafür sorgen, dass es einen Unterschied zwischen "" und " " gibt. Um die Fehlermeldung.

Wenn du dennoch gerne eine spezifische Meldung auch in dem Fall -et -w -pn notepad.exe für -et haben möchtest, müsste man das an einer anderen Stelle einbauen

**Comment by PoppyTheDeveloPaw** [comment]
Erweiterung des Logging bei fehlenden Parameter eingebaut #117
