### ISSUE TITLE
Erweiterung von -et mit Ausgabe der Restzeit

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#111]
Aktuell bekommen wir nur am Ende mit, wenn -et ProcDumpEx terminiert, wie lange ProcDumpEx laufen sollte. Ich denke es könnte sinnvoll sein, beim Start einmalig anzuzeigen wann ProcDumpEx voraussichtlich für diese Instanz terminiert wird. Wir müssen dabei bedenken, das wir N-Instanzen an -et haben können, die über die Config Datei mitgegeben werden könnten. Daher brauchen wir die Endzeit für jede Instanz.

Die Anpassung könnte in der OptionEt.cs wie folgt aussehen:

Zeile 19 - 22 Original:
```
		internal override Task<bool> ExecuteAsync(ProcDumpExCommand command)
		{
			throw new NotImplementedException();
		}

```

Angepasst könnte den Code dann so aussehen, so als Vorschlag:

```
internal override Task<bool> ExecuteAsync(ProcDumpExCommand command)
{
    DateTime endTime = DateTime.Now + TerminationTime;
    Console.WriteLine($"ProcDumpEx will end at: {endTime.ToString("dd/MM/yyyy HH:mm:ss")}");

    return Task.FromResult(true);
}

		{
			throw new NotImplementedException();
		}

```
Ziel ist es, das ich dann ausgegeben bekomme am Anfang:

"ProcDumpEx instance will be terminated due to -et option after <endtime>"

Ich habe im Codevorschlag auch reingepackt, dass das ganze in unserem bekannten Zeitformat ausgegeben wird, damit das auch mit der Logfunktion schön einher geht :)

**Comment by PoppyTheDeveloPaw** [comment]
Ausgabe des erwarteten Endzeitpunkts eingebaut [Issue:111]
