### ISSUE TITLE
Exception bei Eingabe eines Zahlenwertes der höher als 24,8 Tage ist für -et

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#112]
Wenn ich versuche ProcDumpEx versuche einen Zahlenwert mitzugeben, der höher als 24,8 Tagen mitzugeben, erhalte ich eine Exception. Das ist das Parameter:

`procdumpex.exe -w -e -et "90d2h9s" -pn "notepad.exe"`

Das hier die undhandled Exception die ich hier auslöse:
```

Unhandled exception. System.ArgumentException: Invalid value '7783209000' for parameter 'interval'.
   at System.Timers.Timer..ctor(Double interval)
   at ProcDumpEx.ProcDumpExCommand..ctor(List`1 options, List`1 processNames, List`1 processIds, String baseProcDumpCommand, String logId)
   at ProcDumpEx.ProcDumpExCommandParser.Parse(String commandLine, Int32 logId)
   at ProcDumpEx.ArgumentManager.GetCommands(String[] args)
   at ProcDumpEx.Program.Main(String[] args)
   at ProcDumpEx.Program.<Main>(String[] args)

```

Wenn ich die Exception richtig verstehe, scheitern wir hier an dem Timer in .NET, welcher enen maximalen Intervallwert von in.MaxValue Milisekunden hat von etwa 24,8 Tagen. Deswegen kam ich auch den 24,8 ( ;) ). Sobald ich diesen überschreite, haben wir die oben genannte ArgumentException.

Umgehen lässt das wie folgt:

1. Wir konvertieren den gewünschten Gesamtzeitraum in Millisekunden.
2. Wenn der Gesamtzeitraum größer als int.MaxValue ist:
   2.1 Wir setzen das Timer-Intervall auf int.MaxValue.
   2.2 Wir berechnen, wie viele Ticks benötigt werden, um den Gesamtzeitraum zu erreichen.
3. Andernfalls setzen wir das Timer-Intervall auf den Gesamtzeitraum.
4. Jedes Mal, wenn der Timer tickt, erhöhen wir eine Zählvariable.
5. Wenn die Zählvariable die Anzahl der benötigten Ticks erreicht, führen wir die gewünschte Aktion aus.

Im Code könnte das wie folgt aussehen:

Änderung in der ProcDumpExCommand.cs, Zeile 112 - 122:

Original:
```

		private async void TerminationTimer_Elapsed(object? sender, ElapsedEventArgs e)
		{
			if (_etTerminationTimer is null)
			{
				throw new ArgumentException("Internal Error, _etTerminationTimer should never be null, if this method is called.");
			}

			TimeSpan span = TimeSpan.FromMilliseconds(_etTerminationTimer.Interval);
			await StopAsync(TerminationReason.TerminationTimerElapsed);
			ConsoleEx.WriteLog($"ProcDumpEx instance was terminated due to -et option after {Helper.GetFormattedTimeSpanString(span)}.", LogId, LogType.ShutdownLog);
		}

```

**Lösungsvorschlag 1:**

```
		private async void TerminationTimer_Elapsed(object? sender, ElapsedEventArgs e)
		{
			if (_etTerminationTimer is null)
			{
				throw new ArgumentException("Internal Error, _etTerminationTimer should never be null, if this method is called.");
			}

			TimeSpan span = TimeSpan.FromMilliseconds(_etTerminationTimer.Interval);
			await StopAsync(TerminationReason.TerminationTimerElapsed);
			ConsoleEx.WriteLog($"ProcDumpEx instance was terminated due to -et option after {Helper.GetFormattedTimeSpanString(span)}.", LogId, LogType.ShutdownLog);
		}
```

Zusätzlich müssen wir _elapsedTime und die _terminationTime Felder zur ProcDumpExCommand Klasse hinzufügen:

```
private TimeSpan _elapsedTime = TimeSpan.Zero;
private TimeSpan _terminationTime;

```

Zusätzlich müssten wir die _terminationTime im Konstruktor setzen:
```

public ProcDumpExCommand(/*...*/)
{
    /*...*/
    _terminationTime = /* Setzen Sie hier die gewünschte Gesamtzeit */;
    /*...*/
}

```

Danach müssten wire sicherstellen das der Timer in regelmäßgighen Abständen abläuft, die kleiner als die double-Grenze sind. Beispielsweise können wir einen Timer verwenden der dann alle 24 Stunden abläuft:
`
_etTerminationTimer = new Timer(TimeSpan.FromDays(1).TotalMilliseconds);
`
Dabei müssen wir darauf achten das _etTerminationTimer entsprechend initalisiert werden müsste.

**Lösungsvorschlag 2:**

Wir verwenden System.Threading.Timer anstelle von System.Timers.Timer ein. Vorteil hier: SystemThreading.Timer kann Intervall in Millisekunden als long akzeptieren, was bedeutet wir könnten Werte bis zu etwa 292 Millionen Jahre unterstützen. 

codetechnisch würde das dann so aussehen:

```
private Timer _etTerminationTimer;
private long _interval;

public ProcDumpExCommand(/*...*/)
{
    /*...*/
    _interval = (long)optionEt.TerminationTime.TotalMilliseconds;
    _etTerminationTimer = new Timer(TerminationTimer_Elapsed, null, _interval, Timeout.Infinite);
    /*...*/
}

private void TerminationTimer_Elapsed(object? state)
{
    // Timer abgelaufen, ProcDump soll beendet werden
}

```

**Comment by PoppyTheDeveloPaw** [comment]
Es werden jetzt Zeiten bis 10675199.02:48:05 unterstützt: #119
