### ISSUE TITLE
Entfernung der Rückmeldung das Parameter -w terminiert wurde

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#113]
Wie besprochen, hier ein issue, bei dem wir uns einig waren, dass es keinen Sinn macht die Rückmeldung zu erhalten, dass Parameter -w terminiert wurde, weil wir ja bereits die Rückmeldung haben, wenn ProcDumpEx beendet wird oder im idle ist und auf einen Prozess wartet.

Die Änderung müsste in der "OptionW.cs" durchgeführt werden siehe Zeile 50 bis 54:

```
		internal override void StopExecution()
		{
			ConsoleEx.WriteLog("Execution of command '-w' is terminated.", _logId, LogType.Info);
			Dispose();
		}

```

**Comment by PoppyTheDeveloPaw** [comment]
Wurde entfernt mit #120
