### ISSUE TITLE
ProcDumpEx stürzt unter Windows Server 2012 R2 ab (mutmaßlich fehlen Abhängigkeiten)

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#115]
Wenn man versucht ProcDumpEx als Administator unter Windows Server 2012 R2 abstürzt. ProcDump selbst kann auf dem System ausgeführt werden.

Leider ist der Fulldump zu groß, als das ich ihn hier hochladen kann. Daher habe ich dir ihn bereits über einen anderen Weg zukommen lassen.

Mutmaßlich wird es an daran liegen, dass ProcDumpEx hier Abhängigkeiten brauch, die auf dem System nicht vorhanden sind. Hier hatten wir besprochen, dass wir die notwendigen .dll's einfach in der nächsten Version beilegen, um das Problem zu umgehen.

**Comment by PoppyTheDeveloPaw** [comment]
Eine neuere Version der auf dem Windows Server 2012 R2 veralteten Version wird nun mit ausgeliefert #122
