### ISSUE TITLE
"The architecture of the process could not be queried. ProcDumpEx is terminated" bei notepad.exe

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#12]
Wenn ich mehrere notepad.exe Instanzen laufen habe und folgende Parameter verwende, als Administrator ausgeführt:

procdumpex.exe -ma -e -pn "notepad.exe"

Erhalte ich folgende Rückmeldung:

"The architecture of the process could not be queried. ProcDumpEx is terminated"

Hier läuft wohl etwas schief bei der Prüfung der Prozessarchitektur. Notepad.exe müsste in meinem Fall als 64 Bit-Anwendung erkannt werden.

**Comment by Zocoya** [comment]
Ebenfalls reproduzierbar mit dem WindowsTerminal. Auch hier findet ProcDumpEx keine Prozessarchitektur.

Kann durchaus sein, dass man bei WindowsApps die auf dem PC installiert sind, etwas anders vorgehen muss bei der Prüfung.

**Comment by PoppyTheDeveloPaw** [comment]
Wurde mit #28 behoben
