### ISSUE TITLE
Erweiterung des Exceptionhandling für Parameter-cfg

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#127]
Wie besprochen, wollten wir zum Thema Exceptionhandling von -cfg etwas ändern.

Angedacht war soetwas wie ein interner Durchlauf aller Parameter, die in der cfg Datei stehen. Um so, im Falle eines Fehlers ausgeben zu können, in welcher Zeile, welcher Fehler ausgegeben wird. Wir können dabei die Methoden des Errorhandlers verwenden, die wir bereits bereitstellen + der Fehlermeldungen die ProcDump ausgibt im Zweifel, wie wir es aktuell schon in ProcDumpEx tun.

Die Ausgabe könnte dann so aussehen:

Config file found. Checking config file...

<Interne durchlauf aller Zeilen durch ProcDumpEx>

Im Falle eines Fehlers, wäre dann so eine Ausgabe interessant:

Parameters in line <line number> could not be executed:

<error message>

Aktuell haben wir die Bedingung, das alle Parameter stimmen müssen, bevor wir Parameter -cfg verwenden können. ProcDump würde sich identisch verhalten, zu meinem vorgeschlagenen Verhalten verhalten, wenn man anstatt ProcDumpEx, eben eine Batch Datei verwenden würde, um ProcDump anzuweisen.

Denkbar wäre eine Art timeout von einer Sekunde, maximal 2, pro Parameter, damit du die Fehlermeldung abgreifen kannst, die entsteht. Die Fehler müssen dann gesammelt werden und nach dem oben genannten Schema dann ausgegeben werden. Das erleichtert das Debugging enorm.

**Comment by PoppyTheDeveloPaw** [comment]
Wie bereits bei #128 beschrieben, wird für ProcDumpEx keine zusätzliche Prüfung für ProcDump Argumente eingebaut, da diese bereits automatisch bei der ersten Ausführung von ProcDump zu einem Fehler führen würden und zudem der Aufwand durch die optionalen Parameter und Abhängigkeiten untereinander ins unendliche steigen würde. 
Für die Identifizierung der Fehler bei der Verwendung von -cfg war zwar bereits eine Ausgabe drinnen, welche Zeile in welcher Datei genau Fehlerhaft war, diese wurde nun aber nochmal erweitert, so dass auch die restlichen Ausgaben eindeutig zugeordnet werden können.

Wurde gelöst mit #132
