### ISSUE TITLE
Verbessertes Verhalten für die falsche Parametrierung in Kombination mit Parameter -inf

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#128]
Aktuell fluten wir uns bei der falschen Parametrierung in Kombination mit Parameter -inf das Terminal. Wie besprochen soll das Ziel sein, bei einer falschen Parameterierung die weitere Ausführung zu unterbinden und stattdessen eine Fehlermeldung auszugeben.

Dafür müssen wir halt passende Fehlermeldungen erzeugen. Wenn wir hier mehr Arbeit reinstecken wollen, könnten wir eine richtige Prüfung, ob Parameter verwendet werden, die ProcDump oder ProcDumpEx nicht kennt. Somit gegen eine Liste checken von Parametern, die bekannt sind. Im Falle von ProcDump wäre

Hierbei müssen wir zwischen den Dumptypen und Conditions unterscheiden.

Mit allen Parametern die ProcDump und ProcDumpEx kennt würde das im Code beispielsweise so aussehen:
```
      List<string> validParameters = new List<string>
        {
            "-mm", "-ma", "-mt", "-mp", "-mc", "-md", "-mk",
            "-a", "-at", "-b", "-c", "-cl", "-dc", "-e", "-f", "-fx",
            "-g", "-h", "-k", "-l", "-m", "-ml", "-n", "-o", "-p", "-pl",
            "-r", "-s", "-t", "-u", "-v", "-w", "-wer", "-x", "-y", "-64",
            "-cfg", "-memthd", "-cputhd", "-cputhdl", "-inf", "-pn", "-showoutput", "-et"
        };

```
Das wären die Parameter aller Conditions die ProcDump kennt:

```
        Dictionary<string, Action<string>> parameterValidations = new Dictionary<string, Action<string>>
        {
            { "-n", ValidateInteger },
            { "-s", ValidateInteger },
            { "-c", ValidateDouble },
            { "-cl", ValidateDouble },
            { "-m", ValidateInteger },
            { "-ml", ValidateInteger },
            { "-p", ValidateInteger },
            { "-pl", ValidateInteger },
            { "-at", ValidateInteger }

       };
``` 

Hier die Parameter für die Dumptypes:

```
        HashSet<string> dumpTypes = new HashSet<string> { "-mm", "-ma", "-mt", "-mp", "-mc", "-md", "-mk" };

        HashSet<string> providedParams = new HashSet<string>();
        for (int i = 0; i < args.Length; i++)
        {
            string param = args[i];

            if (!validParameters.Contains(param))
            {
                Console.WriteLine($"Ungültiger Parameter: {param}");
                return;
            }

```

**Dumptypes sind nicht untereinander kombinierbar** beispielsweise.

Dann gibt es Parameter die Abhängigkeiten untereinander haben.

Hier ein Beispiel:

Parameter -a hat eine Abhängigkeit zu Parameter -r

Erfüllst du diese Abhängigkeit nicht, erhältst du diese Fehlermeldung von ProcDump:

`
Process cloning via PSS (-r) can't be used with kernel dumping (-mk) due to OS limitations.
`
Parameter -a kann ebenfalls nicht alleine verwendet werden und braucht sinnvollerweise Parameter -r

ProcDump ruft bei Verwendung von der alleinigen Verwendung von Parameter -a die Hilfe auf.

Parameter -g hat eine zwingende Abhängigkeit zu Parameter und -e.

ProcDump Verhalten:

Wir erhalten folgende Fehlermeldung bei alleinigen Verwendung von Parameter -g:

`
Running as just a native debugger (-g) requires exception monitoring (-e) and/or debug logging (-l).
`
Paramater -f und -fx haben jeweils eine zwingende Abhängigkeit zu Parameter -e

ProcDump Verhalten bei falsche Verwendung:
`
Filtering (-f/-fx) requires exception monitoring (-e) and/or debug logging (-l).
`

Dann gibt es Parameter die gar nicht kombinierbar sind:

Parameter -mk kann nicht in Kombination mit Parameter -r verwendet werden.

ProcDump Fehlermeldung:
`
Process cloning via PSS (-r) can't be used with kernel dumping (-mk) due to OS limitations.
`

Parameter -wer ist nicht kompatibel mit Parameter -r in Kombination.

ProcDump Verhalten:

ProcDump gibt dann beispielsweise eine solche Ausgabe aus:
```
[18:40:00] Dump 1 writing: Estimated dump file size is 99 MB.
[18:40:00] Dump 1 complete: 100 MB written in 0.2 seconds
[18:40:01] Waiting for dump to complete...
[18:40:01] WER: Disabled
[18:40:01] Dump count reached.
```
Aber du erhältst anders als ProcDump ausgibt, keinen Dump.

Parameter -w und -x sind nicht kombinerbar.

ProcDump Verhalten:

ProcDump ruft die Hilfe auf.

Parameter -e und Parameter -r sind unter Windows 7 und Windows 8 nicht kombinierbar.

Parameter -k nicht allein verwendbar, sondern sollte mit -r oder -t beispielsweise verwendet werden idealerweise.

Verwendest Parameter -k alleine, erhältst du diese Fehlermeldung:
`
Kill after dump is only valid with AeDebug Just-in-Time support (-i).
`
Parameter -g ist nicht kombinierbar mit Parameter -r

ProcDump Verhalten:

Wenn diese Kombination versucht wird, erhalten wir folgende Fehlermeldung:
`
Running as just a native debugger (-g) requires exception monitoring (-e) and/or debug logging (-l).
`

Parameter -f und x nicht kombinierbar.

ProcDump Verhalten:

Wir erhalten bei der Kombination folgende Fehlermeldung:

`
Filtering (-f/-fx) requires exception monitoring (-e) and/or debug logging (-l).
`

Parameter -p und -pl nicht kombinierbar, da sie sich untereinander widersprechen.

ProcDump Verhalten:

ProcDump ruft beim Versuch der Kombination nur die Hilfe auf.

Parameter -c und -cl nicht kombinierbar, da sie sich untereinander widersprechen.

ProcDump ruft beim Versuch der Kombination nur die Hilfe auf.

Parameter -m und -ml nicht kombinierbar, da sie sich untereinander widersprechen.

ProcDump ruft beim Versuch der Kombination nur die Hilfe auf.

**Alternativ können wir die Rückmeldung an der Stelle von ProcDump auch durchreichen. Dann wären wir flexibler, selbst wenn ProcDump in zukünftigen Versionen, neue Parameter hinzufügt.**

Ich habe nebenbei herausgefunden, das ProcDump verschiedene Status Codes ausgibt, auf die könnten wir ja "lauschen":

_Exit Status: -1_ = Erhalte ich immer dann, wenn ProcDump die Hilfe aufruft beispielsweise mit -? Aber auch, wenn ich Parameter ausführe, bei denen ich die Abhängigkeit zu einem anderen Parameter weg gelassen habe. Grob gesagt: Exit Status 1 bekomme ich für falsche Parametrierung zurück oder Hilfeaufruf, etwa von mir selbst aufgerufen oder wegen einem Fehler.

_Exit Status: -2_= Erhalte ich zurück bei "Zugriff verweigert". Also dann, wenn ProcDump nicht ausreichend Rechte hat, wenn ich es auf einen Prozess hängen will.

_Exit Status: 0_ = Erhalte ich zurück, wenn ich ProcDump mit STRG + C terminiere.

_Exit Status: 1_= Erhalte ich bei einem erfolgreichen Dump zurück.

Die oben genannten Status Codes kommen immer bei der Operation "Process Exit", also beim beenden des ProcDump Prozesses vor.

Im Falle von Fehlermeldungen (also keinem Hilfeaufruf wegen eines fehlers) führt die Procdump.exe eine Operation aus die sich "Debug Output Profiling". Welche in Klartext den Fehler ausgibt, der auch im der Commandline angezeigt wird.

Hinsichtlich zur Verwendung von ProcDumpEx sollten folgende Parameterkombinationen verwendbar sein, da wir hier Ersatzparameter auf ProcDumpEx Seite verwenden und wir eine Dopplung der Parameter hätten:

Parameter -cputhd darf nicht kombinierbar sein mit Parameter -c.
Parameter -cputhdl darf nicht kombiniertbar sein mit Parameter -cl
Parameter -memthd darf nicht kombinierbar sein mit Parameter -m
Parameter -memthdl darf nicht kombinierbar sein mit Parameter -ml

**Comment by PoppyTheDeveloPaw** [comment]
Parameter -inf wird nun bei der Ausführung ignoriert, falls bei der Ausführung von ProcDump die Hilfe ausgegeben wird, was indiziert, dass die angegebenen ProcDump Argumente falsch sind. Eine Prüfung der ProcDump Argumente wird nicht hinzugefügt, da dies bei ProcDump durch optionale Parameter und Abhängigkeiten untereinander ins unendliche gehen würde.

#131
