### ISSUE TITLE
Parameter -et ändern in -ta (TerminateAfter)

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#129]
Während ich die ProcDump Doku nochmal etwas durchgestöbert habe, habe ich gesehen das wir eventuell auf eine Kollision mit einem ProcDump Parameter treffen können siehe Auszug:

-e 	Write a dump when the process encounters an unhandled exception.
Include the 1 to create dump on first chance exceptions.
Add -ld to create a dump when a DLL (module) is loaded (filtering applies).
Add -ud to create a dump when a DLL (module) is unloaded (filtering applies).
Add -ct to create a dump when a thread is created.
**Add -et to create a dump when a thread exits.**

Ansonsten blockieren wir einen ProcDump Parameter.

**Comment by PoppyTheDeveloPaw** [comment]
Fixed with #130
