### ISSUE TITLE
ProcdumpEx / Procdump schreibt Dumpfile nicht bei Verwendung von Parameter -memthd ohne Parameter -w

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#14]
Ich habe festgestellt, das wenn ich "memthd" verwende mit folgenden Parametern, während der Prozess bereits läuft.

"procdumpex.exe -ma -memthd "100,110,120" -pn "<Anwendung>.exe"

Solange ich die Parameter so verwende, wird ProcDumpEx die Session aufrecht erhalten und der Dump von ProcDump wird erst dann geschrieben, wenn ich ProcDumpEx terminiere. Ich erhalte auch keine Rückmeldung darüber, ob der Dump in der Zwischenzeit erzeugt wurde. Nur im Ordner sehe ich nach Terminierung von ProcDumpEx, das die Dumpdateien geschrieben werden.

Im Original erzeugt nach Festlegung und Erreichung des Parameters -m Procdump ein Dumpfile direkt. Das müsste auch hier passieren. 

Es müsste also wie folgt laufen, anhand des Beispiels oben:

Anwendung erreicht 100 MB RAM Verbrauch -> Dump wird geschrieben
Erfolgsmeldung wenn Dump geschrieben wurde 

Anwendung erreicht 110 MB RAM Verbrauch -> Dump wird geschrieben
Erfolgsmeldung wenn Dump geschrieben wurde 

Anwendung erreicht 120 MB RAM Verbrauch -> Dump wird geschrieben
Erfolgsmeldung wenn Dump geschrieben wurde 

Wenn kein Parameter -w verwendet wurde, sollte ProcDumpEx danach terminieren, etwa mit einer Erfolgsmeldung oder mit einer Fehlermeldung, wenn die Dumps aus irgend welchem Gründen nicht geschrieben wurden (eventuell Disk Full oder sowas, wenn das Ganze auftritt).

Mit Parameter -w verhält sich ProcDumpEx korrekt in diesem Moment.

**Comment by PoppyTheDeveloPaw** [comment]
Ich hab das jetzt mal selbst bei mir mit MemTest64 ausprobiert. Funktioniert allerdings wie du auf dem Bild siehst ohne Probleme. Müsstest du mir vllt bei Zeiten nochmal zeigen welche Auswirkung das bei dir hat.

Meine verwendeten Parameter waren: procdumpex.exe -ma -memthd "1000,2000,3000" "MemTest64.exe"

![image](https://user-images.githubusercontent.com/83469470/229366645-38afd04b-9892-49f6-a937-ef7ebd97e838.png)

**Comment by Zocoya** [comment]
Ich teste es bei mir nochmal. Kann ja sein, das ich etwas falsch gemacht habe oder zu ungeduldig war.

**Comment by Zocoya** [comment]
Okay, klappte bei mir doch, dann schließe ich das Thema ab. Lag an mir.
