### ISSUE TITLE
Memthd: Wenn Prozess zwischenzeitlich terminiert wird, kommt keine erneute Rückmeldung mit "Currently there is no process with the name <application>.exe running. Waiting until a process with this name is started."

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#15]
Wenn ich den Parameter -w verwende und die Anwendung nicht gestart wurde bisher, dann erhalte ich korrekterweise die Rückmeldung von ProcDumpEx "Currently there is no process with the name <application>.exe running. Waiting until a process with this name is started.

Sobald der Prozess gestartet wurde, hängt sich ProcDumpEx korrekterweise drauf.

Sobald ich den Prozess aber terminiere, wäre hier die Erwartungshaltung das wieder die Meldung kommt vom Anfang kommt "Currently there is no process with the name <application>.exe running. Waiting until a process with this name is started."

**Comment by PoppyTheDeveloPaw** [comment]
Ja das Problem hierbei ist, dass ProcDumpEx bei der Angabe des Parameters -w ja immer in diesem Zustand des Wartens auf neue Prozesse ist. Wenn ich es immer dann ausgebe, wenn gerade kein ProcDump für den Prozessnamen läuft, dann könnte man es auch so verstehen, dass er nur wartet wenn nicht bereits ein Prozess mit dem Namen gefunden wurde.

Das heißt es wäre eigentlich richtig, dass wenn der Parameter -w angegeben ist ich am Anfang ausgebe, dass auf die angegebenen Prozesse bis zur beendigung von ProcDumpEx gewartet wird und immer wieder neue ProcDump Instanzen gestartet werden sobald ein neuer Prozess gefunden wurde.

**Comment by Zocoya** [comment]
Ich glaube beide Ansätze sind hier richtig. Wenn wir eine Meldung hätten, die sagt "Ich warte auf den Prozess", weiß ich "Okay der Prozess läuft aktuell nicht" und muss erst noch gestartet werden, während die anderen Prozesse, die ich vielleicht mit -pn gewählt habe, sehe das auf diese nicht mehr gewartet wird. Damit habe ich eine Rückmeldung ob einer oder mehrere Prozesse die ich monitoren will, laufen oder auf einen oder mehrere Prozesse noch gewartet wird. Das war der Hintergrund der Anforderung.

Wenn die Dumps geschrieben wurden und aufgrund dessen ProcdumpEx die Instanz erneut startet, beim nächsten Mal wenn der Prozess startet, wäre das auch Feedback das mir sagt, dass beispielsweise eine Exception oder ein Hang in der Zwischenzeit stattgefunden hat und Dumps inzwischen existieren und erneut gewartet wird, bis die Parameter wieder erfüllt werden. Wenn du verstehst was ich meine.

**Comment by PoppyTheDeveloPaw** [comment]
Vllt ist es eine Möglichkeit sobald kein Prozess mehr überwacht wird auszugeben, dass ProcDumpEx sich im Idle-Modus befindet, bis ein neuer Prozess gestartet wird.

So lange ein Prozess überwacht wird sieht man das ja über ProcDumpEx, dass noch nicht alle terminiert wurden

**Comment by Zocoya** [comment]
Es kann ja durchaus sein, dass ein Prozess noch nicht gestartet wurde, zum Start von ProcDumpEx und wir auf den Prozess warten, dann hättest du da ein Feedback zwischenzeitlich, so hatte ich es im Hinterkopf.

Die Idee das ProcdumpEx sich im Idle befindet, finde ich auch nicht schlecht, dann müsste man die Meldung so formulieren, dass zu allen überwachenden Prozessen ein Dumpfile erzeugt wurde und ProcDumpEx als nächstes erst wieder aktiv wird, wenn die Prozesse erneut gestartet werden. Dann wäre es aus meiner Sicht eindeutig formuliert. Ansonsten könnte es eventuell falsch verstanden werden.

**Comment by PoppyTheDeveloPaw** [comment]
> Es kann ja durchaus sein, dass ein Prozess noch nicht gestartet wurde, zum Start von ProcDumpEx und wir auf den Prozess warten, dann hättest du da ein Feedback zwischenzeitlich, so hatte ich es im Hinterkopf.

Aber dafür ist ja die Meldung "Currently there is no process with the name .exe running. Waiting until a process with this name is started." beim Start von ProcDumpEx da um genau das zu informieren

**Comment by Zocoya** [comment]
Richtig, hatte aber als Idee gehabt, wenn ich einen Prozess zwischenzeitlich terminiere, während dem Monitoring, das ich die Rückmeldung erhalte, das wieder auf den Prozess gewartet wird. Das würdest du im Verlauf der Commandline sehen, on der Prozess zwischenzeitlich weg war und gewartet wurde.

Wir können aber auch das Issue schließen, wenn du das nicht für sinnvoll hältst und nur den Hinweis mit ProcdumpEx im Idle einfügen. Kann ich auch mit leben. War ja nur eine Idee gewesen, um mehr Feedback in ProcDumpEx rein zu bekommen :)

**Comment by PoppyTheDeveloPaw** [comment]
Das logging wurde jetzt mit #30 erweitert. Wenn ich eine neue Release baue kannst du es ja mal testen. Will davor nur noch die anderen offenen Issues mal anschauen
