### ISSUE TITLE
Memthd / Memthdl / Cputhd / Cputhdl: Abschließende Rückmeldung, wenn Dumpdateien erfolgreich geschrieben wurden und ProcDumpEx terminiert wird

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#17]
Ist nur ein nice to have: 

Wenn beispielsweise folgende Parameter verwendet werden:

procdumpex.exe -ma -memthd "1,2,3,4,5,6" -pn "<application1>.exe, <application2>.exe" und ProcDumpEx fertig ist mit der Erzeugung der Dumpdateien, dann wäre ein Abschlussmeldung ganz nice. Wenn dann beispielsweise kommt

"Dump(s) successfully created, ProcDumpEx is terminated"

Anstatt einer leeren Kommandozeile. Macht das Konzept von dir konsequenter. Könnte man durchaus auch auf alle anderen Sachen anwenden.

**Comment by PoppyTheDeveloPaw** [comment]
Das Problem ist, dass ich von ProcDump keine Rückmeldung erhalte ob ein Dump erzeugt wurde oder nicht und auch die Ausgabe von ProcDump ist nicht so wirklich eindeutig da. 

Man kann sich allerdings mit dem Argument -showoutput die Ausgabe von ProcDump in der Konsole ausgeben lassen. Vllt hilft dir das schon mehr Informationen zu haben

**Comment by Zocoya** [comment]
Wir könnten auf das Event "ExitedWithDump" schauen, das Procdump auslöst, wenn ein Dump tatsächlich erfolgreich war. Wenn der Dump nicht erfolgreich war, gibt es das Event "ExitedWithoutDump". Dieses Ereignis gibt eine Instanz der Klasse "ProcDumpInfo" zurück. In dieser erhältst du Infos zum Dump-Vorgang zurück und dem Dateipfad des erstellten Dumps. 

Vielleicht hilft dir das?

**Comment by Zocoya** [comment]
Falls das nicht klappt, kann man auch mit dem vorgeschlagenen Parameter von dir arbeiten.

**Comment by PoppyTheDeveloPaw** [comment]
Mit #30 wurde das logging verbessert. In der nächsten Releaseversion gibt es eine Grüne Procdump finished ausgabe wenn es erfolgreich abgeschlossen wurde und gelb wenn es ein Problem gab und kein Dump erzeugt wurde. Außerdem wird angegebenen, wieviele ProcDump Prozesse aktuell aktiv laufen. Falls kein Prozess mehr läuft und -w aktiv ist gibt es eine Ausgabe, dass ProcDumpEx wieder in idle geht.
