### ISSUE TITLE
Featurewunsch: Rückmeldung wenn ProcDumpEx durch den Benutzer terminiert wurde

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#19]
Wenn der Benutzer ProcDumpEx terminiert durch CTRL + C, soll eine rote Meldung in ProcDumpEx kommen wie beispielsweise:

ProcDumpEx has been terminated by user

Wenn die Ursache ein Fehler durch ProcDumpEx war, dann das die Fehlermeldung von ProcDumpEx kommt. Nur damit man ein Feedback erhält ob der Prozess durch jemanden beendet wurde oder durch einen Fehler terminiert wurde (macht es einfacher, wenn man Mal ProcDumpEx debuggen muss).

**Comment by PoppyTheDeveloPaw** [comment]
Ist durch #32 hinzugefügt worden
