### ISSUE TITLE
Featurewunsch: Timestamp für Events in ProcDumpEx

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#20]
Ein Timestamp wäre hier zusätzlich nice, aber kein muss. Damit man sehen kann, wann ProcDumpEx terminiert wurde. Den Timestamp könnte man theoretisch für jeden Eintrag in ProcDumpEx verwenden. Kann man sich überlegen, dass das wie in einem Log aussieht:

<Timestamp> ProcdumpEx Meldung
Der Timestamp sollte am besten in diesem Format sein
<dd.mm.yyyy; hh:mm:ss>

Der Timestamp sollte am besten im UTC-Zeitformat sein, um Probleme mit den unterschiedlichen Zeitzonen vorzubeugen.
Damit man durch ProcDumpEx bereits sieht, wann ein Dump angefangen wurde zu schreiben und wann er fertig wurde usw. 

Kann auch gerade fürs debugging interessant sein oder wenn man ProcDumpEx testet. Gerade wenn man Monitoring Features drin hat, macht es eventuell auch Sinn zu sehen, wann etwas passiert ist, in Abwesenheit.

Kann auch durchaus interessant sein, wenn man ProcDumpEx debuggt, damit man sehen kann, ob etwas in einem regelmäßigen Zeitraum auftritt oder nur sporadisch.

**Comment by PoppyTheDeveloPaw** [comment]
Ist durch #32 und #33 hinzugefügt worden. Format ist [dd.MM.yyyy hh.mm.ss]: Message
