### ISSUE TITLE
Featureidee fürs debuggen von ProcDumpEx: Protokollierungsmodus für ProcDumpEx in eine Logfile.txt

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#21]
Ist nur eine Idee die mir in den Kopf gekommen ist, die dir das debuggen vereinfachen könnte. Wenn man einen Parameter einfügt, der alles was im Zusammenhang mit ProcDumpEx / Procdump passierte, bis zur Terminierung, am Ende in ein Logfile dokumentiert, damit du sehen kannst, was genau passiert ist. Mit dem Timestamp Feature, wüsstest du dann genau, was passiert ist und wann, Danach könntest es leicht versuchen zu reproduzieren.

Denkbar wäre hier der zusätzliche Parameter -log

Der Dateiname des Logfile müsste für die Einzigartigkeit folgendes Format haben:

Logile_yyyymmdd_hhmmss.txt

**Comment by Zocoya** [comment]
Das hier ist kein "must have", sondern nur als Idee lediglich gedacht, damit du ein Logfile erhältst, das dir beim debuggen hilft. Wenn du sagst, das brauchst du für dich nicht, kann das Thema auch geschlossen werden.

**Comment by PoppyTheDeveloPaw** [comment]
Eingebaut mit #34

**Comment by Zocoya** [comment]
Parameter -log funktioniert einwandfrei, eben getestet. Einzige Auffälligkeit das bei den Logeinträgen nicht immer die gleiche Formatierung vorhanden war. Am Anfang und am Ende des Logs haben wir folgende Formatierung:

dd.mm.yyyy hh:mm:ss

Während die Aktionen nur die Uhrzeitangabe enthält siehe Logfile
[Log_20230402_213546.txt](https://github.com/PoppyTheDeveloPaw/ProcDumpEx/files/11133414/Log_20230402_213546.txt)
