### ISSUE TITLE
Versionierung der ProcDumpEx.exe stimmt nicht

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#22]
Die Version von ProcDumpEx steht immer noch auf 1.0.0.0. Zur besseren Übersicht sollte bei jeder Änderung auch die Versionierung stimmen, damit du taggen kannst, was du genau in welcher Version geändert hast.

**Comment by PoppyTheDeveloPaw** [comment]
Mit #36 behoben. Die neuste Release ist jetzt auch veröffentlicht
