### ISSUE TITLE
Parameter -inf nicht funktional

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#23]
Parameter -inf funktioniert nicht Ich bin in der Lage Parameter -n festzulegen für die Anzahl an Dumpdateien, aber sobald Parameter -inf ins Spiel kommt, erhalte ich nach Erfüllung von Parameter -n dann folgende Exception:

"Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at ProcDumpEx.ProcessManager.KillAll()
   at ProcDumpEx.ProcDumpExCommand.Stop()
   at ProcDumpEx.ProcDumpExCommand.StartProcDumpAsync(Process process, String argument)
   at ProcDumpEx.ProcDumpExCommand.StartAllProcDumpCommandsAsync(Process process)
   at ProcDumpEx.ProcDumpExCommand.ExecuteAsync(Int32 processId)
   at ProcDumpEx.ProcDumpExCommand.StartProcDumpAsync(Process process, String argument)
   at ProcDumpEx.ProcDumpExCommand.StartAllProcDumpCommandsAsync(Process process)
   at ProcDumpEx.ProcDumpExCommand.ExecuteAsync(String processName)
   at ProcDumpEx.ProcDumpExCommand.RunAsync()
   at Program.<Main>$(String[] args)
   at Program.<Main>(String[] args)
"
Folgender Parameter wurde verwendet:

procdumpex.exe -ma -cputhdl "20,19,18,17,16,15" -n 2 -inf -pn "<application1>.exe" 

Nach Erzeugung der 2 Dumps, pro angegebenener CPU-Last erhalte ich dann folgende Fehlermeldung:

The architecture of the process could not be queried. ProcDumpEx is terminated

Diese Fehlermeldung wiederholt sich einige Male, bevor sich ProcdumpEx sich terminiert.

Unter memthdl erhalte ich egal ob mit oder ohne Verwendung von Prameter -n die oben genannte Exception.

Es macht den Anschein, als ob wir die ProcDump Session nicht erneut richtig öffnen in Kombination. ProcDump ermöglicht nämlich die erneute Verwendung von ProcDump auf den Prozess. Procdump monitored die CPU-Auslastung per Default für 10 Sekunden (wenn ich Parameter -s nicht festlege). Ansonsten monitored procdump die CPU-Auslastung der in der Länge der Zeit, der mit Parameter -s festgelegt wurde in Sekunden.

Auf Procdumpseite funktionierte das mit folgenden Parametern:

procdump64.exe -ma  -n 2 -cl 20 <application1>.exe (hier schaut sich procdump 10 Sekunden die CPU Last an und schreibt danach 2 Dumps)

procdump64.exe -ma -s 5 -n 2 -cl 20 <application1>.exe hier schaut sich procdump 5 Sekunden die CPU Last an und schreibt danach 2 Dumps).

Auch Parameter oder cputhdl oder memthdl funktionieren nicht mit Parametert -inf. Da scheitert er beim erneuten aufsetzen des Prozesses wieder an der Architekturprüfung des Prozesses mit folgenden Parametern:

procdumpex.exe -ma -inf -pn "<application1>.exe"

Ich erhalte auch hier erneut einige Male diese Fehlermeldung:

"The architecture of the process could not be queried. ProcDumpEx is terminated"

Auch eine Erweiterung der Parameter mit Parameter -w schaffte hier keine Abhilfe.

**Comment by PoppyTheDeveloPaw** [comment]
Sollte mit #31 hoffentlich gefixt sein. Kann mit dem nächsten Release getestet werden
