### ISSUE TITLE
Featurevorschlag: Übergabe der Parameter an ProcDumpEx mittels CONFIG Datei

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#26]
Es würde Sinn machen, wenn man in ProcDumpEx noch einbaut, dass man die Parameter alternativ über eine Config Datei die in Plain-Text geschrieben ist übergibt. So kann man die leicht vorbereiten und kann die dann einem zukommen lassen und sagen "Bitte damit ausführen" und das wars dann.

So könnte die Struktur aussehen:

[Prozess1]
THD=
MA=
[Prozess2]
THD=
MA=
usw...

So könnte man auch für jeden Prozess einzeln die Parameter festlegen, anstatt alle Parameter auf alle Prozesse anzuwenden.

Wenn Parameter -ma für Fulldump verwendet werden soll, müsste dann der Parameter in der Config wie folgt aussehen:

MA= 1

0 wäre dann inaktiv. Wenn ein Parameter einen Wert erwartet wie Parameter -s, so muss dann der Wert für -s angegeben werden beispielsweise. Beispiel:

S= 5

Wenn man ProcdumpEx ohne einen Parameter. Wahlweise könnte man hierfür einen eigenen Parameter einbauen, mit dem man die cfg übergeben kann. Beispielsweise -cfg. Das würde dann so aussehen:

procdumpex -cfg <Name der Config Datei die sich im gleichen Ordner befinden muss wie die Procumpex>.cfg

**Comment by PoppyTheDeveloPaw** [comment]
Wäre es dann nicht sinnvoller dem Nutzer einfach eine bat Datei zu schicken? Sehe gerade nicht ganz den Vorteil 😅
Bzw musst du das mit den verschiedenen Prozessen nochmal erklären. ProcdumpEx erwartet genau einen String an Argumenten mit denen er arbeiten kann. 😅

**Comment by Zocoya** [comment]
Naja Batch Dateien gelten in der IT-Sicherheit als potenziell unsicher. So brauchst du ProcDumpEx nur ausliefern mit der Config und dem Parametern und das wars dann. Das war der Hintergrund :)

**Comment by Zocoya** [comment]
Ich habe nochmal darüber nachgedacht was du geschrieben hast. Der Umbau mit einer Config Datei, wäre deutlich mehr Aufwand. Daher schließe ich das Thema. Es war eine Idee die mir zugetragen wurde, damit man nur noch eine Config schreibt und dann mitgibt, damit man auch nichts mehr falsch machen kann. Hatte es als Idee Mal in den Raum geworfen, ich schließe das Thema,

**Comment by Zocoya** [comment]
Wie besprochen, hatten wir hier die Idee einen eigenen Parameter einzubauen, denkbar wäre hier -cfg <Name der Config-Datei.cfg> und in die kommt dann einfach 1 zu 1 die cmdline Parameter rein, die dann eingelesen werden.

**Comment by PoppyTheDeveloPaw** [comment]
Wurde mit #35 eingebaut.
Es ist allerdings darauf zu achten, dass wenn dieses Feature verwendet wird andere Funktionalität ein wenig in Mittleidenschaft gerissen werden, da durch die vielen Threads beispielsweise die farbliche Protokollierung in der Konsole nicht richtig funktioniert.

**Comment by Zocoya** [comment]
Aber die Protokollierung als solches funktioniert korrekt oder gibt es noch weitere Einschränkungen?

**Comment by PoppyTheDeveloPaw** [comment]
Sie sollte korrekt funktionieren. Wenn ich mir es gerade recht überlege könnte man allerdings eine Id hinzufügen von welchem ProcDumpEx welche Lognachricht kommt. So kann man das vllt besser auseinadnerhalten. Intern ist es so geregelt, dass es ein Objekt gibt pro Zeile die in der Cfg-Datei steht. Diesem Objekt könnte man eine Id geben wodurch das Log vllt übersichtlicher wird. Ich eröffne mir dafür mal selbst ein Issue

**Comment by Zocoya** [comment]
Funktioniert einwandfrei und die farbliche Formatierung war in meinem Fall enthalten, habe noch keinen Fall entdteckt wo sie nicht da war.
