### ISSUE TITLE
Parameter -inf öffnet keine erneute Instanz von Procdump

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#37]
Wenn ich folgende Parameter verwende:

procdumpex.exe -ma -inf -pn "notepad.exe" 

hängt sich ProcDumpEx nicht erneut wieder auf notepad.exe und wird nach dem ersten Dump terminiert. Somit ist Parameter -inf noch nicht funktional.

**Comment by Zocoya** [comment]
Das Verhalten ließ sich mit anderen Anwendungen ebenfalls reproduzieren

**Comment by PoppyTheDeveloPaw** [comment]
#42 Behoben

**Comment by PoppyTheDeveloPaw** [comment]
Das war echt ein richtig dummer Fehler der mir nie aufgefallen ist, weil ich es immer mit -w gleichzeitig verwendet habe was den Fehler umgangen ist 🤦
