### ISSUE TITLE
Logeinträge von -log nicht einheitlich

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#39]
Parameter -log funktioniert einwandfrei, eben getestet. Einzige Auffälligkeit das bei den Logeinträgen nicht immer die gleiche Formatierung vorhanden war. Am Anfang und am Ende des Logs haben wir folgende Formatierung:

dd.mm.yyyy hh:mm:ss

Während die Aktionen nur die Uhrzeitangabe enthält siehe Logfile
[Log_20230402_213546.txt](https://github.com/PoppyTheDeveloPaw/ProcDumpEx/files/11133420/Log_20230402_213546.txt)

**Comment by PoppyTheDeveloPaw** [comment]
#42 Behoben
