### ISSUE TITLE
Zeitstempel nicht mit Uhrzeit überein

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#41]
Ich habe im Timestamp von ProcDumpEx eine Zeitabweichung von 2 Stunden. Vermutlich ging hier etwas bei der Umrechnung der UTC Zeit schief.

Ich habe mir das Logile nochmal angesehen das ich dir bereits in #issue39 bereits bereitgestellt habe. Wenn du genau darauf achtest, haben wir im Logfile 2 unterschiedliche Zeitangaben
[Log_20230402_213546.txt](https://github.com/PoppyTheDeveloPaw/ProcDumpEx/files/11133429/Log_20230402_213546.txt)

**Comment by Zocoya** [comment]
Wenn du darauf achtest, stimmt auch der Zeitstempel im Dateinamen nicht.

**Comment by PoppyTheDeveloPaw** [comment]
> Ich habe im Timestamp von ProcDumpEx eine Zeitabweichung von 2 Stunden. Vermutlich ging hier etwas bei der Umrechnung der UTC Zeit schief.
> 
> Ich habe mir das Logile nochmal angesehen das ich dir bereits in #issue39 bereits bereitgestellt habe. Wenn du genau darauf achtest, haben wir im Logfile 2 unterschiedliche Zeitangaben [Log_20230402_213546.txt](https://github.com/PoppyTheDeveloPaw/ProcDumpEx/files/11133429/Log_20230402_213546.txt)

Dadurch das Sommerzeit ist, sind 2 Stunden Abweichung bei UTC aktuell richtig

**Comment by PoppyTheDeveloPaw** [comment]
> Wenn du darauf achtest, stimmt auch der Zeitstempel im Dateinamen nicht.

Die Zeiten die du meinst, sind die Zeiten die von ProcDump selbst kommen. Die von ProcDumpEx sehen immer nach dem Format [dd.MM.yyyy HH:mm:ss] aus

**Comment by Zocoya** [comment]
Naja wenn wire Zeitabweichungen haben, dann brauchen wir ein anderes Zeitformat, damit die Uhrzeit vom System mit den Logeinträgen zusammen passen. Alternativer Vorschlag:  ISO 8601-Format 

Außer du hast eine andere Idee wie wir das in den Griff bekommen, bin ich völlig offen :)

**Comment by PoppyTheDeveloPaw** [comment]
Wenn du den gleichen Zeitstempel wie procdump willst,  dann müsste man die systemzeit nehmen. Mir ist das im Endeffekt ziemlich egal. Wenn ich weiß, dass wir in UTC loggen, dann weiß ich ja woher die Zeitabweichung kommt. Kann aber auch auf Systemzeit umstellen. Dann stimmt es mit dem log von ProcDump überein

**Comment by PoppyTheDeveloPaw** [comment]
> Naja wenn wire Zeitabweichungen haben, dann brauchen wir ein anderes Zeitformat, damit die Uhrzeit vom System mit den Logeinträgen zusammen passen. Alternativer Vorschlag:  ISO 8601-Format 
> 
> Außer du hast eine andere Idee wie wir das in den Griff bekommen, bin ich völlig offen :)

Das Zeitformat wird nichts an der Tatsache ändern, dass procdump die Systemzeit nutzt und wir gerade UTC 😅 wenn du willst das die beiden Zeiten übereinstimmen, dann müssen wir auch zwangsweise die UTC Zeit nutzen, was ja auch nicht schlimm wäre.

**Comment by PoppyTheDeveloPaw** [comment]
Behoben mit #56
