### ISSUE TITLE
ProcDumpEx Hilfe anpassen

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#45]
Wie besprochen die ProcDumpEx Hilfe anpassen, hierzu habe ich dir zu den neuen Parametern -log und -cfg einen Hilfetext in unsere KB geschrieben, die kannst du copy & paste übernehmen.

**Comment by PoppyTheDeveloPaw** [comment]
Den Text für -cfg habe ich minimal angepasst

`The parameter "-cfg" reads a user-created configuration file. This file contains the command-line parameters with which ProcDumpEx should be started. Several lines can be used to specify different versions of command-line parameters. Each line is treated like a separate ProcDumpEx process.

Examples:
1.	procdumpex.exe -cfg <path of cfg file>

Sample content of SampleFile.txt:

-ma -w -e -inf -pn "<process 1>.exe, <process 2>.exe“
-ma -e -pn „<PID 1>, <PID 2>“
...`

**Comment by Zocoya** [comment]
Das passt. Das würde dann bedeuten, dass das config file mit .txt enden muss, anstatt .cfg, so wie man vom Parameter erwarten würde.

**Comment by PoppyTheDeveloPaw** [comment]
Hinzugefügt mit #59
