### ISSUE TITLE
Überschrift für die ProcDumpEx Hilfe (Uns als Autoren von ProcDumpEx eintragen)

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#46]
ProcDump verwendet diese Überschrift:

ProcDump v11.0 - Sysinternals process dump utility
Copyright (C) 2009-2022 Mark Russinovich and Andrew Richards
Sysinternals - www.sysinternals.com

Um uns dem anzugleichen könnte unsere Überschrift über der ProcDumpEx Hilfe sein:

ProcDumpEx v"Versionsnummer" - Extension to Microsoft's Sysinternal Tool ProcDump
Copyright (C) "Dein Name" and "Mein Name"

Und darunter dann der ganze Hilfetext von ProcDumpEx. 

Wäre doch eine coole Idee. Das Einzige woran man hier denken müsste, dass nicht nur die Dateiversion passt, sondern auch die Versionsnummer. Aber theoretisch könnte man hier eine Variable einsetzen, die befüllt wird mit der Dateiversion von ProcDumpEx. Das müsste eigentlich gehen. Abgesehen davon wäre das ganze so seriöser aus meiner Sicht, da es weniger nach einem "U-Boot Projekt" aussieht, sondern, auch tatsächlich die Autoren genannt werden :D

Abgesehen davon haben wir bisher noch nichts eingebaut, mit der du die Versionsnummer von ProcDumpEx innerhalb der Kommandozeile ausgeben lassen kannst. So macht es ProcDump auch, wieso nicht auch daran halten? ;)

**Comment by PoppyTheDeveloPaw** [comment]
Hinzugefügt mit #60
