### ISSUE TITLE
Procdumpex mit procdumpex anstatt procdumpex.exe ansprechen

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#47]
Du hattest das hier Mal als Punkt bei dir auf der Liste, das du mal schauen wolltest, das es auch ausreicht ProcDumpEx so anzusprechen:

procdumpex -ma -e -pn "process1.exe"

anstatt so

procdumpex.exe -ma -e -pm "process1.exe"

War kein must have, war aber ein Punkt der dich Mal gestört hat. Kann als Idee ganz nach hinten gesetzt werden, wenn der Aufwand größer ist. Wichtiger sind das die Grundfunktionalitäten erst einmal bugfrei sind :)

**Comment by PoppyTheDeveloPaw** [comment]
Das wäre eine Konfiguration die man am eigenen PC ausführen müsste.
Wenn man es über die Eingabeaufforderung (CMD) machen möchte, dann reicht es die Datei ProcDumpEx.exe umzubenennen in procdumpex oder eine Verknüpfung zu der Datei ProcDumpEx.exe mit dem Namen procdumpex zu erstellen.

In PowerShell muss man hierfür einen Alias eintragen, das geht wie folgt:
Set-Alias -Name procdumpex -Value "C:\Pfad\Zur\Ausführbaren\Datei\ProcDumpEx.exe"

Von meiner Seite kann aus kann ich da nicht viel machen

**Comment by Zocoya** [comment]
Gut, dann haken wir das Thema ab. Ich hatte den Punkt auf die Liste gesetzt, weil du meintest du wolltest dir das nochmal ansehen, weil es ProcDump auch könnte.

Wenns nicht geht, geht es nicht.
