### ISSUE TITLE
ProcDumpEx erzeugt keine Dumps, wenn auf dem System nicht mindestens einmal die Eula von ProcDump akzeptiert wurde

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#51]
Wenn ProcDump auf einem System noch nie ausgeführt wurde und ich es zum ersten Mal mit Parametern betreibe, erhalte ich einmalig einen prompt mit der Eula von ProcDump. Erst wenn ich diese akzeptiert habe, funktioniert ProcDump ordnungsgemäß.

Dieses Prompt erhalten wir bei ProcDumpEx nicht, was dazu führt, dass wir lediglich Abbruchsmeldungen in ProcDumpEx erhalten, dass der Dump nicht erzeugt werden konnte. 

Leider habe ich noch nicht rausbekommen, welches Event ProcDump da genau triggert, auf das wir schauen könnten. Das Problem ist, sobald du einmal auf einem System die Eula akzeptiert hast, kommt sie nie wieder, was das testen immer etwas blöd macht. Ich werde das mal mit Procmon in einer VM beobachten.

**Comment by Zocoya** [comment]
So, ich habe raus bekommen, wo ProcDump seinen Regkey für das akzeptieren der Eula-Bedingungen ablegt.

Sobald erstmalig bei ProcDump die Eula akzeptiert wird, wird in folgendem Registrypfad geschrieben:

Computer\HKEY_USERS\"Registrykey des aktuell eingeloggten Benutzers"\Software\Sysinternals\ProcDump

In diesem Pfad legt ProcDump einen DWORD-Wert (32-Bit) ab mit der Bezeichnung "EulaAccepted" und dem Wert 1 (Hexadezimal) ab

Wenn die Eula abgelehnt wurde auf dem System, wird dieser Regwert gar nicht erst erzeugt. Ist der Regwert ungültig, beispielsweise wenn ich in 0 setze oder ich lösche den Key einfach. Möchte ProcDump die Eula von ProcDump erneut bestätigen. Lehne ich die Eula ab, bleibt der ungültige Regwert erhalten, bestätige ich die Eula, wird der von mir auf 0 geänderte "EulaAccepted" Regwert auf 1 abgeändert und ProcDump fragt mich nicht mehr nach der Bestätigung der Eula.

ProcDump hat es auch akzeptiert, wenn ich den Regwert selbst händisch korrekt gesetzt habe.

Der Registrykey des aktuellen eingelogten Benutzers begann in meinen 2 Beobachtungen unter Win 10 und Win 11 mit S-1-5-21 und endete immer mit -1001 (nicht verwechseln mit -1001_Classes).

Somit müsste man aus meiner Sicht nur prüfen ob der aktuell eingeloggte User diesen Regkey gesetzt hat, wenn nicht, gibt es aus meiner Sicht 4 Möglichkeiten. 

1.Etwa wir setzen durch ProcDumpEx den Regwert selbst, wenn er nicht gesetzt ist

2.Wir prüfen ob der Regwert gesetzt ist, wenn nicht, fügt ProcDumpEx bei der ersten Parametrierung den Parameter -accepteula hinzu und damit setzt ProcDump den Regkey wieder selbst

3.Wir sprechen procdump beim ersten Mal einfach an, da reicht es, wenn wir -help aufrufen und unterdrücken, dann geht der Eula Prompt bereits auf oder du gibst so einen Unsinn wie: procdump -v weiter, dann kommt zwar so eine Ausgabe:

ProcDump v11.0 - Sysinternals process dump utility
Copyright (C) 2009-2022 Mark Russinovich and Andrew Richards
Sysinternals - www.sysinternals.com

No process matching the specified name can be found.
Try elevating the command prompt or using PsExec to make one as SYSTEM.
        psexec.exe -s -d -i cmd.exe
        procdump.exe -accepteula ...

aber die könnte man unterdrücken und wir hätten das Prompt auf dem regulären Weg sichtbar gemacht wie ProcDump es macht und ProcDump setzt selbst seinen Regwertr und das wars.

4.Wir starten ProcDumpEx und geben beim start schon automatisch "procdump -accepteula" an ProcDump und das Thema wäre auch erledigt.

**Comment by PoppyTheDeveloPaw** [comment]
Fehler wurde durch #63 behoben. Es gibt jetzt vorher eine Prüfung und man kann direkt von ProcDumpEx aus der Eula zustimmen oder diese ablehnen. Bei Ablehnung wird ProcDumpEx beendet.
