### ISSUE TITLE
Featurevorschlag: Neuer Parameter -et (execution time) zur Ergänzung von Parameter -w

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#52]
Es wurde ein Vorschlag an mich heran getragen, das Parameter -w ja bis ins endlose wartet auf einen Prozess und somit fürs Monitoring ja nicht schlecht ist, aber es auch interessant wäre, wenn ich einen Zeitraum angeben könnte indem, ProcdumpEx auf einen Prozess wartet und danach soll ProcDumpEx komplett terminieren.

Damit hättest du ein messbares Ergebnis für einen Zeitraum, vorher musstest du aufwändig mit Parameter -n und -s hantieren (also rumrechnen) wie lange Dumps gezogen werden, die Zeitangabe war dann immer in Sekunden.

So könnte der Parameter -et aussehen:

ProcDumpEx -ma -e -et ddd:hh:mm:ss -pn "process1.exe,process2.exe"

Somit könnte man die Zeit etwa so angeben:

ProcDumpEx -ma -e -et 3d2h30m30s -pn "process1.exe,process2.exe"

Wie der Zeitraum bemessen werden soll:

Sobald ProcDumpEx läuft, soll die Zeit gemessen werden und in dann am Ende ProcDumpEx terminiert werden komplett (als hättest du ProcDumpEx mit CTRL + C beendet) dabei soll auch in der cmd eine Meldung kommen, die darauf hinweist, das ProcDumpEx terminiert wurde aufgrund von -et.

Gerade für die Analyse nicht schlecht, wenn man etwas reproduzieren möchte und prüfen will, ob ein Verhalten genauso wie beschrieben auftritt.

**Comment by Zocoya** [comment]
Es müssten hierfür folgende Änderungen am Code gemacht werden:

- Neue Klasse unter Options hinzufügen beispielsweise "WaitTimeOption"

Diese könnte folgenden Code enthalten:

`public static TimeSpan ParseWaitTime(string waitTime)
{
    var match = Regex.Match(waitTime, @"^(?:(\d+)d)?(?:(\d+)h)?(?:(\d+)m)?(?:(\d+)s)?$");

    if (!match.Success)
        throw new ArgumentException("Invalid wait time format. The correct format is ddd:hh:mm:ss.");

    var days = match.Groups[1].Success ? int.Parse(match.Groups[1].Value) : 0;
    var hours = match.Groups[2].Success ? int.Parse(match.Groups[2].Value) : 0;
    var minutes = match.Groups[3].Success ? int.Parse(match.Groups[3].Value) : 0;
    var seconds = match.Groups[4].Success ? int.Parse(match.Groups[4].Value) : 0;

    return new TimeSpan(days, hours, minutes, seconds);
}`

- Logik für diese Funktion in der ProcessManager.cs einbauen mithilfe der Task.Delay Methode um eine Verzögerung zu erzeugen und dann die Environment,Exit-Methode aufrufen um ProcDumpEx zu beenden. Das könnte wie folgt aussehen:

`public async Task MonitorProcesses(WaitTimeOption waitTimeOption)
{
    // Start monitoring processes...

    await Task.Delay(waitTimeOption.WaitTime);

    Console.WriteLine("ProcDumpEx was terminated due to -wt option.");
    Environment.Exit(0);
}`

- Anpassung an der MonitorProcesses-Methode in der Program.cs Datei:

`var waitTimeOption = new WaitTimeOption { WaitTime = ParseWaitTime(/* parsed wait time string */) };
var processManager = new ProcessManager();
await processManager.MonitorProcesses(waitTimeOption);`

**Comment by PoppyTheDeveloPaw** [comment]
Wurde mit #108 hinzugefügt
