### ISSUE TITLE
Wenn ProcDumpEx nicht als Admin gestartet wird, öffnet sich ein neues Fenster in der ProcDumpEx einfach als Admin gestartet wird

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#53]
Wenn ProcDumpEx ohne Adminrechte ausgeführt wird, wird eine neue Session geöffnet, die ProcDumpEx einfach als Admin ausführt, ohne Rückfrage des Benutzers. Lerdiglich die UAC (Benutzerkontensteuerung von Windows) weist mich darfaufhin, das sich ProcDumpEx gerade Administrationsrechte verschaffen möchte, ohne zu wissen warum. Man hat zwar eine funktionierende ProcDumpEx Session, aber der Benutzer wird nicht gefragt und nimmt dem Benutzer die Kontrolle. Darüber hinaus, wird das Fenster der Session sofort geschlossen, nach beenden der Session. Somit sehe ich auch nicht was in der Commandline passiert.

Daher sollte das wie folgt angepasst werden. Wenn ProcDumpEx ohne Adminrechte gestartet wird, sollte in Rot diese Nachricht kommen:

ProcDumpEx was started without administrative privileges. Without administrative privileges, ProcDumpEx cannot be used properly. Should ProcDumpEx execute a new session and start as an administrator? Type y (yes) to continue or n (no) to exit ProcDumpEx.

Somit lässt sich diese Sache mit bool umsetzen und man hat die Kontrolle zurück. Wenn der Benutzer y eintippt, soll eine neue cmd geöffnet werden als Administrator ausgeführt und dieses Fenster offen bleiben, als hätte ich cmd ganz normal aufgerufen, damit das Fenster sich nicht wieder schließt.

Sollte das alles so nicht umsetzbar sein, kann man es auch so lösen, das ProcDumpEx nur folgende Nachricht ausgibt, wenn es nicht als Admin gestartet wurde, in roter Farbe:

ProcDumpEx was started without administrative privileges. To use ProcDumpEx properly, please start ProcDumpEx as an administrator.

Und danach soll ProcDumpEx gar nichts mehr machen. 

2 Lösungsvorschläge die beide okay sind. Wobei die erste Lösung zu bevorzugen wäre.

**Comment by PoppyTheDeveloPaw** [comment]
https://stackoverflow.com/questions/2532769/how-to-start-a-process-as-administrator-mode-in-c-sharp

Am besten so umsetzen, dass Prozess in Konsole ausgeführt wird und der alte beendet wird.

**Comment by Zocoya** [comment]
Müsste ich mir ansehen wie die Lösung genau aussieht. Wir sollten nur aufpassen, dass Parameter wie -log oder potenziell -cfg auch damit ausgeführt werden können. Das habe ich in der Kombination ehrlicherweise noch nicht getestet.

**Comment by PoppyTheDeveloPaw** [comment]
Ist jetzt auf Lösungsvorschlag 2 hinausgelaufen, dass nur die Fehlermeldung kommt, dass ProcDumpEx mit Administratorberechtigung gestartet werden muss und man die Konsole aus der man es ausführt als Administrator starten soll. Eine nicht als Administrator gestartete Konsole mit einem C# Programm zu ändern ist nicht möglich.

Fix in #55
