### ISSUE TITLE
Fehlerbehebung was auf dem Bild zu sehen ist

### ISSUE THREAD

**Issue by PoppyTheDeveloPaw** [PoppyTheDeveloPaw/ProcDumpEx#54]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/83469470/234222006-75e5b238-55ec-43f9-abec-91e10e2c2603.png)

**Comment by PoppyTheDeveloPaw** [comment]
procdumpex.exe -ma -inf -pn "Notepad.exe" "C:\temp\ProcDumpEx\Crashdumps"

**Comment by PoppyTheDeveloPaw** [comment]
@Zocoya Also es lag ein wenig an beiden, falsche Ausführung und Fehler im Programm.

Man will jetzt ja haben, dass am Ende von der Ausführung der Ordner angegeben wird und nicht die ID. Da im Normalfall aber immer am Ende die ID rein kopiert wird von ProcDumpEx, muss man nun aktiv die Stelle angeben bei der die ID des Prozesses eingesetzt werden sollte.
Der Aufruf würde dann also im Endeffekt wie folgt aussehe:
procdumpex.exe -ma -inf -pn "Notepad.exe" [ProcessPlaceholder] "C:\temp\ProcDumpEx\Crashdumps"

An der Stelle von [Placeholder] wird dann die ID des Prozesses eingesetzt von ProcDumpEx.

Fehler wurde in #62 behoben

**Comment by Zocoya** [comment]
Ich glaube an dieser Stelle denken wir hier ein wenig zu komplex. 

Wenn ich explizit die PID auswählen möchte, kann ich ja -pn "PID1 "<Angabe vom Pfad>"". Was konkret bedeutet, schreibe mir den Dump von PID 1 in diesen Ordner, von PID  2 in diesen Ordner. 

Was aber auch gehen sollte ist, das ich hinter -pn einfach nur den Pfad angebe wo die Dumps alle hin geschrieben werden sollte. Also die Pfadangabe auf alles was sich in -pn befindet anwende.

Das ich also sowas machen kann:

procdumpex.exe -ma -e -pn "notepad.exe,firefox.exe" "<Pfad in den die Dumps geschrieben werden sollen". 

Damit beide Lösungen funktionieren. Dann hast du aus meiner Sicht alle Varianten gelöst. Da ich -pn ohne Angabe von PID, auf alle Instanzen anwenden kann.

Wären wir konsequent, müsste diese Konstellation auch funktionieren:

procdumpex.exe -ma -e -pn "<process 1>.exe "<Angabe des Pfads>",<process 2>.exe "<Angabe des Pfads>""

Dann hast du alle Fälle abgedeckt und diese Funktion voll zur Verfügung gestellt.

**Comment by PoppyTheDeveloPaw** [comment]
Mit #65 wurde hier noch eine weitere Funktion eingefügt, dass an der Stelle von PN nun der Prozess eingefügt wird, wenn man nicht selbst bereits in den Übergabeparametern [ProcessPlaceholder] angegeben hat.
