### ISSUE TITLE
ProcDumpEx wartet auf einen Prozess mit Parameter -inf, aber wenn der Prozess gestartet ist, findet ProcDumpEx den Prozess nicht

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#68]
Folgenden Fall habe ich getestet:

Wenn du folgende Parameter verwendest und Notepad.exe nicht gestartet ist:

procdumpex.exe -ma -t -inf -pn "notepad.exe"

Erklärung zu Parameter -t: Parameter -t steht für "terminate" und wird ausgelöst, wenn eine gestartete Anwendung beendet wird, durch einen selbst oder durch den Taskmanager von Windows. Danach wird ein Dump erzeugt.

Bekomme ich von ProcDumpEx die Meldung, dass aktuell kein Prozess läuft, der diesen Namen trägt. Was korrekt ist. Bis hierhin soweit so gut. Starte ich notpad.exe, wird kein Dump erzeugt. Auch das ist korrektes Verhalten. Aber ProcDumpEx verhält sich, als ob er auf diesen Prozess wartet und schreibt auch in die cmd "Currently there is no process with the name notepad.exe running. The execution for this process name is terminated.".

Korrektes Verhalten müsste sein, das wenn ich ProcDumpEx **ohne Parameter -w starte und die Anwendung nicht gestartet ist,** das ProcDumpEx die Rückmeldung gibt, dass kein Prozess mit dem Namen gefunden wurde und terminiert.

Du kannst das in Procdump testen mit folgenden Parametern:

procdump -ma -t notepad.exe

wichtig ist das du notepad nicht gestartet ist, dann wirst du sehen das Procdump terminiert und dir diese Rückmeldung gibt "No process matching the specified name can be found."

**Comment by PoppyTheDeveloPaw** [comment]
behoben durch #74
