### ISSUE TITLE
-cfg arbeitet nicht korrekt mit Parameter -w zusammen

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#69]
Wenn ich eine Config Datei erzeuge mit folgendem Inhalt:

procdumpex.exe -ma -w -t -log -pn "notepad.exe"
procdumpex.exe -ma -w -t -log -pn "mspaint.exe"

Verwendete ProcDumpEx Parameter: procdumpex.exe -cfg testconfig.txt

Beide Prozesse sind nicht gestartet am Anfang. Dann starte ich notepad und dann paint. Daraufhin erhalte ich die Ausgaben:

[1][26.04.2023 14:35:12]: procdump64.exe terminated without success. Id: 20792, Examined process: Notepad. Number of active monitored processes: 1
[2][26.04.2023 14:35:31]: procdump64.exe terminated without success. Id: 1424, Examined process: mspaint. Number of active monitored processes: 0

Wenn du jetzt aber mal ProcDumpEx mit den in der Config angeführten Parametern oben einzeln startest, funktioniert es. Ich bin mir nicht sicher, aber ich glaube hier wird einfach Parameter -w nicht angesprochen.

Logfile und meine testconfig habe ich dir hier angehängt

[testconfig.txt](https://github.com/PoppyTheDeveloPaw/ProcDumpEx/files/11332853/testconfig.txt)

[Log_20230426_143300.txt](https://github.com/PoppyTheDeveloPaw/ProcDumpEx/files/11332855/Log_20230426_143300.txt)

**Comment by PoppyTheDeveloPaw** [comment]
Das Verhalten hier ist komplett richtig, das Problem ist hier, dass du nicht zwei mal ProcDump auf den gleichen Prozess mit den Parametern anwenden kannst:

Glaube du hast da vllt auch ausversehen die falsche Log Datei kopiert. Mit dem Parameter -showoutput würdest du auch direkt in der Konsole den Fehler sehen. In der richtigen LogDatei müsste 

[2][26.04.2023 17:46:33]: ProcDump v11.0 - Sysinternals process dump utility
[2][26.04.2023 17:46:33]: Copyright (C) 2009-2022 Mark Russinovich and Andrew Richards
[2][26.04.2023 17:46:33]: Sysinternals - www.sysinternals.com
[2][26.04.2023 17:46:33]: 
[2][26.04.2023 17:46:33]: Error debugging process:
[2][26.04.2023 17:46:33]: The process is already being debugged.

**Comment by Zocoya** [comment]
Ich habe ProcDumpEx auf zwei verschiedene Prozesse gehängt. Das eine ist Notepad, das andere Paint.

Ich reproduziere es gerne nochmal und schicke das Logfile gerne

**Comment by Zocoya** [comment]
Okay, du hast Recht. Das ist das falsche Logfile. Es wird tatsächlich gar kein Logfile damit erzeugt am Ende.

Und ein Dump wird auch nicht geschrieben, wenn ich Notepad oder Paint beende. Versuch es mal selbst.

Geh in den ProcDump64 Ordner und sprich ProcDump64 mit folgenden Parametern an:

procdump64 -ma -w -t notepad.exe 

und starte im Anschluss Notepad und schließe es wieder. Du wirst sehen du hast einen Dump. ProcDumpEx wiederum erzeugt dir keinen Dump und kein Logfile.

![2023-04-26 18_06_20-Administrator_ Eingabeaufforderung](https://user-images.githubusercontent.com/129038733/234635286-6fe7f017-c617-486a-87cf-620d7bbcc555.png)

**Comment by PoppyTheDeveloPaw** [comment]
![image](https://user-images.githubusercontent.com/83469470/234637914-64b41f24-2d15-48cb-bda3-81411ddbdf0b.png)
Das ist echt immer ein wenig blöd wenn ich Fehler so gar nicht nachstellen kann 😂

[cfg.txt](https://github.com/PoppyTheDeveloPaw/ProcDumpEx/files/11335103/cfg.txt)


Hab diese cfg file verwendet.

**Comment by PoppyTheDeveloPaw** [comment]
Also allgemein macht der Pariser an der Stelle gerade alles richtig, da er einfach nicht davon ausgeht, dass ProcDumpEx.exe mit in der cfg Datei steht. Auf dem Bild mit der Ausgabe von dir sieht man auch, dass er procdumpex.exe einfach als Parameter weiter durch schleift, weil er mit dem Wert nichts anfangen kann.

-![Screenshot_20230426_222434_Brave.jpg](https://user-images.githubusercontent.com/83469470/234694489-647fdb3b-15dd-400f-96c3-040a5d955d48.jpg)

Ich werde aber dennoch nicht mit einbauen, dass man auch procdumpex.exe mit eingeben könnte, also beides akzeptiert wird und das Programm procdumpex.exe einfach ignoriert wenn es drinnen steht.

**Comment by PoppyTheDeveloPaw** [comment]
Wird in issue #77 weiter verfolgt
