### ISSUE TITLE
Erweiterung der Abhängigkeitssuche zu ProcDump

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#7]
Es soll auch möglich sein, dass ProcDumpEx einfach zusammen in einen Ordner mit Procdump.exe und ProcDump64.exe abgelegt wird und gestartet werden kann.

**Comment by Zocoya** [comment]
Thema erledigt, da procdump.exe die procdump64.exe löscht, sobald diese sich im gleichen Ordner befinden und die procdump64.exe wieder temporär durch procdump.exe erzeugt wird.

**Comment by PoppyTheDeveloPaw** [comment]
Es ist nun möglich die procdump.exe, procdump64.exe und procdump64a.exe mit in den Ordner von procdumpex.exe zu legen
