### ISSUE TITLE
Farbenwunsch: Wenn ProcDumpEx nicht als Admin ausgeführt, Meldung in roter Farbe

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#70]
Wenn ProcDumpEx nicht als Admin ausgeführt wird, ist das ja ein Fehler vom Nutzer, den würde ich zur Abhebung rot einfärben, anstatt blau, da wir die Farbe nehmen, das ProcDumpEx im Idle ist. Damit man ein paar Farbcodes haben:

Blau = Hinweis
Gelb= Warnung
Rot= Fehler
Grün = Erfolg

So hatten wir es bisher gemacht. Konkret hat der Benutzer ja einen Fehler gemacht. Um diese Meldung geht es konkret:

[Helper][26.04.2023 15:09:12]: Administrator privileges are required to run ProcDumpEx. Please restart the console as administrator.

**Comment by PoppyTheDeveloPaw** [comment]
eingebaut durch #74
