### ISSUE TITLE
Parameter -help unsere Namen in der Help File ohne ""

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#71]
Du hattest unsere Namen in Anführungszeichen eingesetzt. In der Original Hilfe von ProcDump stehen die Namen auch nicht in Anführungszeichen drin. Das sollten wir hier auch tun um die gleiche Struktur zu haben

**Comment by PoppyTheDeveloPaw** [comment]
behoben mit #75
