### ISSUE TITLE
Featurevorschlag für Parameter -cfg: Kommentierung innerhalb der cfg zulassen

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#72]
Man könnte beispielsweise sich eine CFG Datei bauen, die alle Anweisungen enthält, die man sonst immer wieder verwendet. Kommentare im Code werden ja bekanntlich mit ##<Kommentar> gekennzeichnet.

Kommentare sollen vom Parser ignoriert werden. So könnte man sich seine Kommandos dokumentieren und die Kommandos ein- oder auskommentieren, damit du sie beispielsweise nutzen kannst.

Ist nur eine Idee, kein must have.

**Comment by Zocoya** [comment]
Die Anpassung könnte in der OptionCfg.cs wie folgt aussehen, damit Kommentare die mit // und # beginnen, erlaubt sind:

namespace ProcDumpEx.Options
{
    [Option("-cfg", true)]
    internal class OptionCfg : OptionBase
    {
        internal string FilePath { get; }
        internal override bool IsCommandCreator => false;

        public OptionCfg(string path)
        {
            FilePath = path;
        }

        internal string[] GetArgumentsFromFile()
        {
            if (!string.IsNullOrEmpty(FilePath))
            {
                if (!File.Exists(FilePath))
                    throw new ManageArgumentsException("The specified config path is invalid");

                var lines = File.ReadAllLines(FilePath);

                string toRemoveAtStart = "procdumpex.exe ";
                const string COMMENT_CHAR_1 = "//";
                const string COMMENT_CHAR_2 = "#";

                for (int i = 0; i < lines.Length; i++)
                {
                    if (lines[i].StartsWith(toRemoveAtStart, StringComparison.OrdinalIgnoreCase))
                    {
                        lines[i] = lines[i].Substring(toRemoveAtStart.Length);
                    }

                    // Skip comments
                    if (lines[i].Trim().StartsWith(COMMENT_CHAR_1) || lines[i].Trim().StartsWith(COMMENT_CHAR_2))
                        continue;
                }

                return lines;
            }
            return new string[0];
        }

        internal override Task<bool> ExecuteAsync(ProcDumpExCommand command)
        {
            throw new NotImplementedException();
        }
    }
}

**Comment by PoppyTheDeveloPaw** [comment]
Erledigt mit #105
