### ISSUE TITLE
Bug: Cmd Schriftfarbe ändert sich in die zuletzt verwendete Farbe, wenn ProcDumpEx mit STRG + C beendet wird und die letzte Ausgabe in einer anderen Farbe als weiss ist

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#73]
Zugegeben diesen Fehler konnte ich nur durch ein bisschen provozieren herausfinden, indem ich mit ProcDumpEx gespielt habe.

Es wurde folgender Parameter verwendet:
C:\temp\procdumpex (2)>procdumpex.exe -cfg testconfig2.txt

Innerhalb der Config wurden folgende Parameter verwendet:
procdumpex.exe -ma -log -inf -pn "procdumpex.exe"
procdumpex.exe -ma -log -inf -pn "procdumpex.exe"
procdumpex.exe -ma -log -inf -pn "procdumpex.exe"
procdumpex.exe -ma -log -inf -pn "procdumpex.exe"

Ich weiß nicht sonderlich sinnbehaftet, aber so bin ich zufällig darüber gestolpert. Wenn du STRG +C drückst in einem Augenblick, in der eine andere Schriftfarbe verwendet wurde, so ist die Farbe der cmd ebenfalls in dieser Farbe. 

Hier die Config, das Protokoll und der Screenshot:

[testconfig2.txt](https://github.com/PoppyTheDeveloPaw/ProcDumpEx/files/11334516/testconfig2.txt)

[Log_20230426_171203.txt](https://github.com/PoppyTheDeveloPaw/ProcDumpEx/files/11334519/Log_20230426_171203.txt)

![2023-04-26 17_12_35-Log_20230426_171203 - Editor](https://user-images.githubusercontent.com/129038733/234622272-ce86b221-b602-418b-91be-eea46d09f3c7.png)

**Comment by PoppyTheDeveloPaw** [comment]
Behoben mit #78
