### ISSUE TITLE
Unhandled Exception: "Unhandled exception. System.Exception: Unable to read PEB."

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#81]
Wenn du ProcDumpEx auf einen Prozess anwendest, bei dem ProcDumpEx trotz Adminrechte nicht ausreichend Rechte hat um einen Dump zu erzeugen von dem Prozess, so erhältst du folgende Exception:

```
Unhandled exception. System.Exception: Unable to read PEB.
   at Gapotchenko.FX.Diagnostics.Pal.Windows.ProcessEnvironment._GetPEnv(IntPtr hProcess)
   at Gapotchenko.FX.Diagnostics.Pal.Windows.ProcessEnvironment._GetEnvStream(IntPtr hProcess)
   at Gapotchenko.FX.Diagnostics.Pal.Windows.ProcessEnvironment.ReadVariables(IntPtr hProcess)
   at Gapotchenko.FX.Diagnostics.Pal.Windows.PalAdapter.ReadProcessEnvironmentVariables(Process process)
   at Gapotchenko.FX.Diagnostics.ProcessExtensions.ReadEnvironmentVariables(Process process)
   at ProcDumpEx.ProcessEx.GetProcessArchitecture(Process process) in C:\Users\alexa\Documents\GitHub\ProcDumpEx\code\ProcessEx.cs:line 16
   at ProcDumpEx.ProcDumpExCommand.GetProcDumpPath(Process process) in C:\Users\alexa\Documents\GitHub\ProcDumpEx\code\ProcDumpExCommand.cs:line 307
   at ProcDumpEx.ProcDumpExCommand.StartProcDumpAsync(Process process, String argument) in C:\Users\alexa\Documents\GitHub\ProcDumpEx\code\ProcDumpExCommand.cs:line 248
   at ProcDumpEx.ProcDumpExCommand.StartAllProcDumpCommandsAsync(Process process) in C:\Users\alexa\Documents\GitHub\ProcDumpEx\code\ProcDumpExCommand.cs:line 216
   at ProcDumpEx.ProcDumpExCommand.ExecuteAsync(Int32 processId) in C:\Users\alexa\Documents\GitHub\ProcDumpEx\code\ProcDumpExCommand.cs:line 224
   at ProcDumpEx.ProcDumpExCommand.RunAsync() in C:\Users\alexa\Documents\GitHub\ProcDumpEx\code\ProcDumpExCommand.cs:line 120
   at Program.<Main>$(String[] args) in C:\Users\alexa\Documents\GitHub\ProcDumpEx\code\Program.cs:line 30
   at Program.<Main>(String[] args)
```
Wenn du das mit ProcDump versuchst, erhältst von ProcDump Seite folgende Rückmeldund:

``
Error opening lsass.exe (1540):
Zugriff verweigert (0x00000005, 5)
``
Reproduzierbar von ProcDumpEx Seite mit folgenden Parametern:

procdumpex.exe -ma -pn "lsass.exe"

Hintergrundinfo zur lsass.exe:

Die lsass.exe ist eine ausführbare Datei in Microsoft Windows-Betriebssystemen. Sie steht für "Local Security Authority Subsystem Service" und ist für die Verwaltung der Sicherheitsrichtlinien, Authentifizierung und Benutzerautorisierung zuständig. Sie spielt eine wichtige Rolle beim Anmelden von Benutzern und stellt sicher, dass nur autorisierte Benutzer auf das System zugreifen können.

Wir haben also für die lsass.exe nicht ausreichend Rechte, somit wäre das erwartete Verhalten ProcDumpEx, dass eine rote Fehlermeldung zurückkommt mit der Meldung:

ProcDumpEx was unable to access <process_placeholder>.exe. Please make sure that ProcDumpEx has sufficient privileges during execution and try again.

**Comment by Zocoya** [comment]
Die Änderungen müssten aus meiner Sicht in der ProcessEx.cs angepasst werden. 

Zum einen haben wir kein Exceptionhandling drin, wenn wir für den Prozessorarchitektur den Wert "null" oder "empty" erhalten. Zum anderen lässt  sich das Problem mit einem zusätzlichen catch abfangen. Die Codeanpassung könnte dann so aussehen:

using Gapotchenko.FX.Diagnostics;
using ProcDumpExExceptions;
using System.Collections.Specialized;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.InteropServices;

namespace ProcDumpEx
{
    internal static class ProcessEx
    {
        // Constant for the key used to get the processor architecture from the environment variables
        private const string ProcessorArchitecture = "PROCESSOR_ARCHITECTURE";

        // Extension method for the Process class to get the processor architecture
        internal static ProcessorArchitecture GetProcessArchitecture(this Process process)
        {
            try
            {
                // Read the environment variables of the process
                var dictionary = process.ReadEnvironmentVariables();

                // If the dictionary does not contain the key "PROCESSOR_ARCHITECTURE", throw an exception
                if (!dictionary.TryGetValue(ProcessorArchitecture, out var value))
                    throw new GetArchitectureException();

                // If the value is null or empty, throw an exception
                if (string.IsNullOrEmpty(value))
                    throw new ArgumentException("The value for processor architecture is null or empty.");

                // Check if the value is a valid enum value
                if (!Enum.TryParse(typeof(ProcessorArchitecture), value, true, out var result))
                    throw new InvalidEnumArgumentException($"The value '{value}' is not a valid processor architecture.");

                // Parse the value into a ProcessorArchitecture enum
                return (ProcessorArchitecture)result;
            }
            catch (Exception ex)
            {
                // If any exception occurs while trying to get the process architecture, throw a new exception with a custom error message
                throw new Exception("Failed to get process architecture. The process may require higher privileges than administrator.", ex);
            }
        }

        // Helper method to try to get a value from the StringDictionary
        private static bool TryGetValue(this StringDictionary dict, string key, out string? value)
        {
            value = null;
            // If the dictionary contains the key, get the value and return true
            if (dict.ContainsKey(key))
            {
                value = dict[key];
                return true;
            }
            // If the dictionary does not contain the key, return false
            return false;
        }
    }

    // Enum for the different processor architectures
    enum ProcessorArchitecture
    {
        x86,
        AMD64,
        x64,
        ARM,
        ARM64,
    }
}

**Comment by PoppyTheDeveloPaw** [comment]
Erledigt mit #104
